version: "3.7"
services:
    vsftpd:
        image: panubo/vsftpd
        environment:
            - FTP_USER=admin
            - FTP_PASSWORD=qwerty
        volumes:
            - ./cosas:/srv
        expose:
            - 21
        network_mode: host
