version: "3"
services:
    mysql-db:
        container_name: base-mysql
        image: mysql
        volumes:
            - "vol_01:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: test
            MYSQL_USER: raagus
            MYSQL_PASSWORD: userpass
        ports:
            - "3307:3306"
volumes:
    vol_01:

